# Generated by Django 6.0.5 on 2026-05-21 12:03

from django.db import migrations, models


PROMO_TYPE_MAP = {
    'BRAKE15': ['Тормозная система'],
    'FILTER10': ['Фильтры'],
    'OILWEEK': ['Масла и жидкости'],
    'KYBPLUS': ['Подвеска'],
    'LIGHT7': ['Оптика'],
    'SUMMERCOOL': ['Двигатель', 'Масла и жидкости'],
    'APRILPARTS': ['Фильтры', 'Масла и жидкости'],
}


def assign_promo_product_types(apps, schema_editor):
    PromoCode = apps.get_model('shop', 'PromoCode')
    ProductType = apps.get_model('shop', 'ProductType')
    types = {name: pk for name, pk in ProductType.objects.values_list('name', 'pk')}
    for code, type_names in PROMO_TYPE_MAP.items():
        try:
            promo = PromoCode.objects.get(code=code)
        except PromoCode.DoesNotExist:
            continue
        promo.product_types.set(types[name] for name in type_names if name in types)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='product_types',
            field=models.ManyToManyField(blank=True, help_text='Пусто — промокод действует на любой товар.', related_name='promo_codes', to='shop.producttype', verbose_name='Типы товаров'),
        ),
        migrations.RunPython(assign_promo_product_types, migrations.RunPython.noop),
    ]
